add_newline = true

format = '$all$directory[â¯](red)[â¯](blue)[â¯](green)$character'

[time]
disabled = false
format = 'ğŸ•™[\[ $time \]](white) '
time_format = '%T'
utc_time_offset = '+9'

[aws]
style = 'blue'

[git_branch]
style = 'bold purple'

[gcloud]
style = 'blue'

[git_status]
style = 'purple'
conflicted = '[ = ](red)'
ahead = ' â‡¡${count} '
behind = ' â‡£${count} '
diverged = ' â‡•â‡¡${ahead_count}â‡£${behind_count} '
up_to_date = '[ âœ“ ](green)'
untracked = '[ â—¼ ](blue)'
stashed = '[ âœ­ ](yellow)'
modified = '[ âœ± ](green)'
staged = '[ ++\($count\) ](green)'
renamed = '[ âœ ](blue)'
deleted = '[ âœ– ](red)'

[directory]
style = 'green'